apiVersion: v1
kind: Pod
metadata:
  name: pets-app
  labels:
    app: pets-app
spec:
  containers:
    - name: petsapp
      image: kammana/pets-app:commit_hash
      ports:
        - containerPort: 8080
